### ISSUE TITLE
Formatting the paragraphs 

### ISSUE THREAD

**Issue by mrpan13** [ArthurFDLR/whisper-youtube#10]
Is it possible to format the text file after getting the transcript from Whisper?

I try to implement the method from 
https://medium.com/@npolovinkin/how-to-chunk-text-into-paragraphs-using-python-8ae66be38ea6.

and 

https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#prepare

not sure how should I combine these code tgt

**Comment by ArthurFDLR** [comment]
The `whisper-youtube` Notebook generates transcription files of various types (e.g. `txt`, `srt`, `json`) in your Google Drive. So you can easily load one of these files in another Python script (or any application) for your own custom post-processing.

If you prefer to integrate the source code you mentioned, feel free to branch this repository and modify the Notebook to your needs.
