### ISSUE TITLE
Note: More sources that YouTube works

### ISSUE THREAD

**Issue by StaffanBetner** [ArthurFDLR/whisper-youtube#11]
I noticed that I e.g. instead of a YouTube link could enter a link to a podcast episode and it worked just as well. Maybe something to change in the notebook?

**Comment by ArthurFDLR** [comment]
The Notebook relies on `yt-dlp` to download videos. While this package's primary focus is Youtube, [it also supports many other websites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md). And I don't think there's any strong argument for restricting the ingestion to Youtube videos only.

**Comment by StaffanBetner** [comment]
My point was that it is a good idea to point out that more material than YouTube videos works, not that it should be restricted to only YouTube videos.
