### ISSUE TITLE
Error when transcripting

### ISSUE THREAD

**Issue by BlockSats** [ArthurFDLR/whisper-youtube#12]
Hello,
I've been using Whisper with whisper_youtube.ipynb for a while to transcribe mentorship sessions in English, which I then translate into French. 

Everything was working fine, but lately I've been having problems.

Previously when I select a playlist it worked perfectly. Now "video selection" module will recognize the video list, but when I launch the transcription I'll get an error.
Lastly, I was transcribing from .wav files available on my Google Drive, and when I switched to another folder of video extracted in .wav also from the same source, I automatically got the following error when I reached 100% of transcription.

NameError: name 'transcript_local_path' is not defined

However, it's exactly the same folder that is set as the destination

et le message complet :

`/content/ICT Mentorship Core Content - Month 1 - 3 - Equilibrium Vs. Premium.wav
100%|██████████| 125889/125889 [01:09<00:00, 1807.09frames/s]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-85-7fdbc63fadf8>](https://localhost:8080/#) in <cell line: 102>()
    128                 transcript_file_name = video_path_local.stem + "." + ext
--> 129                 shutil.copy(
    130                     video_path_local.parent / transcript_file_name,

2 frames
FileNotFoundError: [Errno 2] No such file or directory: '/content/ICT Mentorship Core Content - Month 1 - 3 - Equilibrium Vs. Premium.txt'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
[<ipython-input-85-7fdbc63fadf8>](https://localhost:8080/#) in <cell line: 102>()
    141 
    142     except:
--> 143         display(Markdown(f"**Transcript file created: {transcript_local_path}**"))

NameError: name 'transcript_local_path' is not defined`

**Comment by BlockSats** [comment]
I'm having trouble with this message again
I can't figure out where the error is coming from, since it's random

`TypeError: get_writer.<locals>.write_all() missing 1 required positional argument: 'options' site:stackoverflow.com`
`NameError: name 'transcript_local_path' is not defined site:stackoverflow.com`
`NameError: name 'Path' is not defined site:stackoverflow.com`

**Comment by ArthurFDLR** [comment]
Thanks for raising the issue. I haven't been able to reproduce the bug, but I updated the section of the Notebook to clean up error handling. Please let me know if it has fixed (or at least clarified) your issue. Otherwise, please provide more details about your configuration or a copy of the Notebook with the error.
