### ISSUE TITLE
How to remove time stamp

### ISSUE THREAD

**Issue by DAmrGharieb** [ArthurFDLR/whisper-youtube#13]
Hi team,
Good day,
I came across the notebook and really impressed and want the text to be generated without time stamp could you help me in that
thanks

**Comment by S1M0N38** [comment]
In the `Parameter` section there is the `output_format` selector.

![Screenshot 2023-12-10 at 17 25 09](https://github.com/ArthurFDLR/whisper-youtube/assets/22257750/b5b4000d-7c1e-4af9-be6d-8b4516fdd3d9)

The `txt` format save the generated text in plain text without timestamp. You can also select `all`, so all formats will be produced and then you can choose the one that best suite you.

**Comment by ArthurFDLR** [comment]
Thank you for the explanation @S1M0N38.
