### ISSUE TITLE
Transcribe multiple vids (from youTube)

### ISSUE THREAD

**Issue by Abdurrafey-Siddiqui** [ArthurFDLR/whisper-youtube#2]
Hi @ArthurFDLR can you please add some code which lets you to transcribe multiple vids at the same time. Just so its not time consuming to do it separately. Thanks!

**Comment by ArthurFDLR** [comment]
Hey @Venomous912, thanks for the input. I just updated the Notebook to support batch processing:
- All videos within a Youtube playlist;
- All video/audio files in a Google Drive folder;
