### ISSUE TITLE
Gdrive

### ISSUE THREAD

**Issue by xvegasus404** [ArthurFDLR/whisper-youtube#4]
Transcription with Google drive does not work.
The application stays intact and nothing happens if you can fix this it will be great.

thank you for your work

**Comment by ArthurFDLR** [comment]
Thanks for raising the issue; should be fixed in https://github.com/ArthurFDLR/whisper-youtube/commit/c7a8c1933dd5bf3d3528fc3f50394e3ccaedbe88.
