### ISSUE TITLE
write_all() missing 1 required positional argument: 'options'

### ISSUE THREAD

**Issue by bymechul** [ArthurFDLR/whisper-youtube#7]
I get this error when transcribing my video in google drive.

Traceback (most recent call last)

[<ipython-input-7-efc615e79dd2>](https://localhost:8080/#) in <cell line: 102>()
    111 
    112     # Save output
--> 113     whisper.utils.get_writer(
    114         output_format=output_format,
    115         output_dir=video_path_local.parent

TypeError: write_all() missing 1 required positional argument: 'options'

**Comment by n8tbyte** [comment]
I just tried this for the first time and I got the same error.

**Comment by n8tbyte** [comment]
i think error from this commit: [https://github.com/openai/whisper/commit/43940fc9780cb91c4f94899755b4648e19d7b977](https://github.com/openai/whisper/commit/43940fc9780cb91c4f94899755b4648e19d7b977)

![image](https://user-images.githubusercontent.com/33704769/231854753-2536988f-bcaf-4348-8c7e-ae829116235b.png)

**Comment by bymechul** [comment]
> i think error from this commit: [openai/whisper@43940fc](https://github.com/openai/whisper/commit/43940fc9780cb91c4f94899755b4648e19d7b977)
> 
> ![image](https://user-images.githubusercontent.com/33704769/231854753-2536988f-bcaf-4348-8c7e-ae829116235b.png)

I think so. But this project also needs to be fixed.

**Comment by n8tbyte** [comment]
### You may use my version. to wait for the main version to update.

[https://github.com/naruepanart/google-colab-whisper](https://github.com/naruepanart/google-colab-whisper)

**Comment by bymechul** [comment]
> ### You may use my version. to wait for the main version to update.
> https://github.com/naruepanart/google-colab-whisper

OK thanks. I will feedback.

**Comment by bymechul** [comment]
> ### You may use my version. to wait for the main version to update.
> 
> https://github.com/naruepanart/google-colab-whisper


the application takes no action.

**Comment by ArthurFDLR** [comment]
Thanks for raising the issue and finding the source of the bug! I fixed the problem in 63088b9c9cf98b10ef6218cc33a2e98678833c5f.
